apiVersion: v1
kind: Service
metadata:
  name: hello-server
  namespace: default
  labels:
    app: hello-server
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6789
      nodePort: 32081
  selector:
    app: hello-server
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
