apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"mageai"}]},"output":{"containers":[{"limits":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"mageai"}]},"modified":true}'
    autopilot.gke.io/warden-version: 2.8.74
    deployment.kubernetes.io/revision: "1"
  labels:
    app: hello-server
  name: hello-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-server
    spec:
      initContainers:
      - name: empty-volume
        image: busybox
        volumeMounts:
        - name: mageai-volume
          mountPath: /data
        command: ["/bin/sh", "-c", "rm -rf /data/*"]
      - name: copy-files
        image: minhut/debian-lib
        volumeMounts:
        - name: mageai-volume
          mountPath: /data
        command: ["sh", "-c", "cp -R /usr/local/lib/R/site-library/* /data/"]
      containers:
      # - image: minhut/debian-lib:lastest
      - image: mageai/mageai
      # - image: python:3.10-bookworm
        volumeMounts:
        - name: mageai-volume
          mountPath: /usr/local/lib/R/site-library
        imagePullPolicy: Always
        name: mageai
        resources:
          limits:
            cpu: 1
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 2Gi
            memory: 1Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64  
      volumes:
      - name: mageai-volume
        persistentVolumeClaim:
          claimName: mageai-pvc